//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model()
        {
            this.AddInktoStores = new HashSet<AddInktoStore>();
        }
    
        public int Model_Id { get; set; }
        public string Model_Name { get; set; }
        public int Brand_Id { get; set; }
        public int Color_Id { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddInktoStore> AddInktoStores { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
    }
}
