//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreUser
    {
        public int StoreUserID { get; set; }
        public int Store_Id { get; set; }
        public int UserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
